using System;
using System.Linq;
using System.Collections.ObjectModel;
using Domain.Common;
using Domain.Features.Payrolls.Aggregates;
using Domain.Features.Payrolls.Entities;
using Domain.Features.Payrolls.Enums;
using Domain.Features.Payrolls.Aggregates.Payments;
using Xunit;
using FluentAssertions;

namespace Domain.Features.Payrolls
{
    public class PayrollTests
    {
        [Fact]
        public void Constructor_WithValidParameters_ShouldCreatePayroll()
        {
            // Arrange
            var employeeId = Guid.NewGuid();
            var periodStart = new DateTime(2024, 1, 1);
            var periodEnd = new DateTime(2024, 1, 31);

            // Act
            var payroll = new Payroll(employeeId, periodStart, periodEnd);

            // Assert
            payroll.Id.Should().NotBeEmpty();
            payroll.EmployeeId.Should().Be(employeeId);
            payroll.PeriodStart.Should().Be(periodStart);
            payroll.PeriodEnd.Should().Be(periodEnd);
            payroll.Status.Should().Be(PayrollStatus.Draft);
            payroll.GrossAmount.Should().Be(0);
            payroll.TotalDeductions.Should().Be(0);
            payroll.NetAmount.Should().Be(0);
            payroll.Components.Should().BeEmpty();
        }

        [Theory]
        [InlineData("Invalid period: end date before start date")]
        [InlineData("Invalid period: end date equals start date")]
        public void Constructor_WithInvalidPeriod_ShouldThrowArgumentException(string description)
        {
            // Arrange
            var employeeId = Guid.NewGuid();
            var periodStart = new DateTime(2024, 1, 31);
            var periodEnd = new DateTime(2024, 1, 1);

            // Act
            Action act = () => new Payroll(employeeId, periodStart, periodEnd);

            // Assert
            act.Should().Throw<ArgumentException>().WithMessage("*Invalid payroll period*");
            
            description.Should().NotBeNullOrEmpty();
        }

        [Fact]
        public void Constructor_WithEmptyEmployeeId_ShouldThrowArgumentException()
        {
            // Arrange
            var periodStart = new DateTime(2024, 1, 1);
            var periodEnd = new DateTime(2024, 1, 31);

            // Act
            Action act = () => new Payroll(Guid.Empty, periodStart, periodEnd);

            // Assert
            act.Should().Throw<ArgumentException>().WithMessage("*EmployeeId is required*");
        }

        [Fact]
        public void AddComponent_WhenInDraftState_ShouldAddComponent()
        {
            // Arrange
            var payroll = CreateValidPayroll();
            var component = new PayrollComponent(
                PayrollComponentType.BaseSalary,
                PayrollComponentCategory.Earning,
                "Base Salary",
                1000m,
                Guid.NewGuid());

            // Act
            payroll.AddComponent(component);

            // Assert
            payroll.Components.Should().HaveCount(1);
            payroll.Components.First().Should().Be(component);
        }

        [Fact]
        public void AddComponent_WhenNotInDraftState_ShouldThrowInvalidOperationException()
        {
            // Arrange
            var payroll = CreateValidPayrollWithComponents();
            payroll.MarkAsCalculated();
            var component = new PayrollComponent(
                PayrollComponentType.BaseSalary,
                PayrollComponentCategory.Earning,
                "Base Salary",
                1000m,
                Guid.NewGuid());

            // Act
            Action act = () => payroll.AddComponent(component);

            // Assert
            act.Should().Throw<InvalidOperationException>().WithMessage("*Cannot modify payroll unless it is in Draft state*");
        }

        [Fact]
        public void AddComponent_WithDuplicateRule_ShouldThrowInvalidOperationException()
        {
            // Arrange
            var payroll = CreateValidPayroll();
            var ruleId = Guid.NewGuid();
            var component1 = new PayrollComponent(
                PayrollComponentType.BaseSalary,
                PayrollComponentCategory.Earning,
                "Base Salary",
                1000m,
                ruleId);
            var component2 = new PayrollComponent(
                PayrollComponentType.BaseSalary,
                PayrollComponentCategory.Earning,
                "Base Salary 2",
                1100m,
                ruleId);

            payroll.AddComponent(component1);

            // Act
            Action act = () => payroll.AddComponent(component2);

            // Assert
            act.Should().Throw<InvalidOperationException>().WithMessage("*Component generated by this rule already exists*");
        }

        [Fact]
        public void MarkAsCalculated_WithValidEarnings_ShouldTransitionToCalculated()
        {
            // Arrange
            var payroll = CreateValidPayrollWithComponents();
            var deductionComponent = new PayrollComponent(
                PayrollComponentType.LegalDeduction,
                PayrollComponentCategory.Deduction,
                "Tax",
                100m,
                Guid.NewGuid());
            
            payroll.AddComponent(deductionComponent);

            // Act
            payroll.MarkAsCalculated();

            // Assert
            payroll.Status.Should().Be(PayrollStatus.Calculated);
            payroll.GrossAmount.Should().Be(1000m);
            payroll.TotalDeductions.Should().Be(100m);
            payroll.NetAmount.Should().Be(900m);
        }

        [Fact]
        public void MarkAsCalculated_WithoutEarnings_ShouldThrowInvalidOperationException()
        {
            // Arrange
            var payroll = CreateValidPayroll();
            var deductionComponent = new PayrollComponent(
                PayrollComponentType.LegalDeduction,
                PayrollComponentCategory.Deduction,
                "Tax",
                100m,
                Guid.NewGuid());
            
            payroll.AddComponent(deductionComponent);

            // Act
            Action act = () => payroll.MarkAsCalculated();

            // Assert
            act.Should().Throw<InvalidOperationException>().WithMessage("*Payroll must contain at least one earning*");
        }

        [Fact]
        public void MarkAsCalculated_WhenNotInDraftState_ShouldThrowInvalidOperationException()
        {
            // Arrange
            var payroll = CreateValidPayrollWithComponents();
            payroll.MarkAsCalculated();

            // Act
            Action act = () => payroll.MarkAsCalculated();

            // Assert
            act.Should().Throw<InvalidOperationException>().WithMessage("*Payroll can only be calculated from Draft state*");
        }

        [Fact]
        public void Approve_WhenCalculated_ShouldTransitionToApproved()
        {
            // Arrange
            var payroll = CreateValidPayrollWithComponents();
            payroll.MarkAsCalculated();

            // Act
            payroll.Approve();

            // Assert
            payroll.Status.Should().Be(PayrollStatus.Approved);
        }

        [Fact]
        public void Approve_WhenAlreadyApproved_ShouldThrowInvalidOperationException()
        {
            // Arrange
            var payroll = CreateValidPayrollWithComponents();
            payroll.MarkAsCalculated();
            payroll.Approve();

            // Act
            Action act = () => payroll.Approve();

            // Assert
            act.Should().Throw<InvalidOperationException>().WithMessage("*Payroll is already approved*");
        }

        [Fact]
        public void Approve_WhenAlreadyPaid_ShouldThrowInvalidOperationException()
        {
            // Arrange
            var payroll = CreateValidPayrollWithComponents();
            payroll.MarkAsCalculated();
            payroll.Approve();
            payroll.MarkAsPaid();

            // Act
            Action act = () => payroll.Approve();

            // Assert
            act.Should().Throw<InvalidOperationException>().WithMessage("*Payroll is already been paid*");
        }

        [Fact]
        public void Approve_WhenNotCalculated_ShouldThrowInvalidOperationException()
        {
            // Arrange
            var payroll = CreateValidPayroll();

            // Act
            Action act = () => payroll.Approve();

            // Assert
            act.Should().Throw<InvalidOperationException>().WithMessage("*Payroll must be calculated before approval*");
        }

        [Fact]
        public void MarkAsPaid_WhenApproved_ShouldTransitionToPaid()
        {
            // Arrange
            var payroll = CreateValidPayrollWithComponents();
            payroll.MarkAsCalculated();
            payroll.Approve();

            // Act
            payroll.MarkAsPaid();

            // Assert
            payroll.Status.Should().Be(PayrollStatus.Paid);
        }

        [Fact]
        public void MarkAsPaid_WhenNotApproved_ShouldThrowInvalidOperationException()
        {
            // Arrange
            var payroll = CreateValidPayrollWithComponents();
            payroll.MarkAsCalculated();

            // Act
            Action act = () => payroll.MarkAsPaid();

            // Assert
            act.Should().Throw<InvalidOperationException>().WithMessage("*Payroll must be approved first*");
        }

        [Fact]
        public void MarkAsPaid_WhenAlreadyPaid_ShouldThrowInvalidOperationException()
        {
            // Arrange
            var payroll = CreateValidPayrollWithComponents();
            payroll.MarkAsCalculated();
            payroll.Approve();
            payroll.MarkAsPaid();

            // Act
            Action act = () => payroll.MarkAsPaid();

            // Assert
            act.Should().Throw<InvalidOperationException>().WithMessage("*Payroll is already been paid*");
        }

        [Fact]
        public void AddMilestonePayment_WhenInDraftState_ShouldAddPayment()
        {
            // Arrange
            var payroll = CreateValidPayroll();
            var milestoneRuleId = Guid.NewGuid();
            var amount = 500m;
            var paidAt = DateTime.UtcNow;

            // Act
            payroll.AddMilestonePayment(milestoneRuleId, amount, paidAt);

            // Assert
            payroll.MilestonePayments.Should().HaveCount(1);
            var payment = payroll.MilestonePayments.First();
            payment.MilestoneRuleId.Should().Be(milestoneRuleId);
            payment.Amount.Should().Be(amount);
            payment.PaidAt.Should().Be(paidAt);
        }

        [Fact]
        public void AddMilestonePayment_WhenInCalculatedState_ShouldAddPayment()
        {
            // Arrange
            var payroll = CreateValidPayrollWithComponents();
            payroll.MarkAsCalculated();
            var milestoneRuleId = Guid.NewGuid();
            var amount = 500m;
            var paidAt = DateTime.UtcNow;

            // Act
            payroll.AddMilestonePayment(milestoneRuleId, amount, paidAt);

            // Assert
            payroll.MilestonePayments.Should().HaveCount(1);
        }

        [Fact]
        public void AddMilestonePayment_WhenNotInDraftOrCalculatedState_ShouldThrowInvalidOperationException()
        {
            // Arrange
            var payroll = CreateValidPayrollWithComponents();
            payroll.MarkAsCalculated();
            payroll.Approve();
            var milestoneRuleId = Guid.NewGuid();

            // Act
            Action act = () => payroll.AddMilestonePayment(milestoneRuleId, 500m, DateTime.UtcNow);

            // Assert
            act.Should().Throw<InvalidOperationException>().WithMessage("*Cannot add milestone payment unless payroll is Draft or Calculated*");
        }

        [Fact]
        public void AddMilestonePayment_WithDuplicateRule_ShouldThrowInvalidOperationException()
        {
            // Arrange
            var payroll = CreateValidPayroll();
            var milestoneRuleId = Guid.NewGuid();
            payroll.AddMilestonePayment(milestoneRuleId, 500m, DateTime.UtcNow);

            // Act
            Action act = () => payroll.AddMilestonePayment(milestoneRuleId, 600m, DateTime.UtcNow);

            // Assert
            act.Should().Throw<InvalidOperationException>().WithMessage("*This milestone rule was already applied to this payroll*");
        }

        [Fact]
        public void IsMilestonePaid_WithExistingPayment_ShouldReturnTrue()
        {
            // Arrange
            var payroll = CreateValidPayroll();
            var milestoneRuleId = Guid.NewGuid();
            payroll.AddMilestonePayment(milestoneRuleId, 500m, DateTime.UtcNow);

            // Act
            var result = payroll.IsMilestonePaid(milestoneRuleId);

            // Assert
            result.Should().BeTrue();
        }

        [Fact]
        public void IsMilestonePaid_WithoutExistingPayment_ShouldReturnFalse()
        {
            // Arrange
            var payroll = CreateValidPayroll();
            var milestoneRuleId = Guid.NewGuid();

            // Act
            var result = payroll.IsMilestonePaid(milestoneRuleId);

            // Assert
            result.Should().BeFalse();
        }

        [Fact]
        public void AddAguinaldoPayment_WhenInDraftState_ShouldAddPayment()
        {
            // Arrange
            var payroll = CreateValidPayroll();
            var ruleId = Guid.NewGuid();
            var amount = 1000m;
            var paidAt = DateTime.UtcNow;

            // Act
            payroll.AddAguinaldoPayment(ruleId, amount, paidAt);

            // Assert
            payroll.AguinaldoPayments.Should().HaveCount(1);
            var payment = payroll.AguinaldoPayments.First();
            payment.AguinaldoRuleId.Should().Be(ruleId);
            payment.Amount.Should().Be(amount);
            payment.PaidAt.Should().Be(paidAt);
        }

        [Fact]
        public void AddVacationPayment_WhenInDraftState_ShouldAddPayment()
        {
            // Arrange
            var payroll = CreateValidPayroll();
            var ruleId = Guid.NewGuid();
            var amount = 300m;
            var paidAt = DateTime.UtcNow;

            // Act
            payroll.AddVacationPayment(ruleId, amount, paidAt);

            // Assert
            payroll.VacationPayments.Should().HaveCount(1);
            var payment = payroll.VacationPayments.First();
            payment.VacationRuleId.Should().Be(ruleId);
            payment.Amount.Should().Be(amount);
            payment.PaidAt.Should().Be(paidAt);
        }

        [Fact]
        public void AddProductivityPayment_WhenInDraftState_ShouldAddPayment()
        {
            // Arrange
            var payroll = CreateValidPayroll();
            var ruleId = Guid.NewGuid();
            var amount = 200m;
            var paidAt = DateTime.UtcNow;

            // Act
            payroll.AddProductivityPayment(ruleId, amount, paidAt);

            // Assert
            payroll.ProductivityPayments.Should().HaveCount(1);
            var payment = payroll.ProductivityPayments.First();
            payment.ProductivityRuleId.Should().Be(ruleId);
            payment.Amount.Should().Be(amount);
            payment.PaidAt.Should().Be(paidAt);
        }

        [Fact]
        public void AddOvertimePayment_WhenInDraftState_ShouldAddPayment()
        {
            // Arrange
            var payroll = CreateValidPayroll();
            var ruleId = Guid.NewGuid();
            var amount = 150m;
            var paidAt = DateTime.UtcNow;

            // Act
            payroll.AddOvertimePayment(ruleId, amount, paidAt);

            // Assert
            payroll.OvertimePayments.Should().HaveCount(1);
            var payment = payroll.OvertimePayments.First();
            payment.OvertimeRuleId.Should().Be(ruleId);
            payment.Amount.Should().Be(amount);
            payment.PaidAt.Should().Be(paidAt);
        }

        [Fact]
        public void AddDeductionPayment_WhenInDraftState_ShouldAddPayment()
        {
            // Arrange
            var payroll = CreateValidPayroll();
            var ruleId = Guid.NewGuid();
            var amount = 50m;
            var appliedAt = DateTime.UtcNow;

            // Act
            payroll.AddDeductionPayment(ruleId, amount, appliedAt);

            // Assert
            payroll.DeductionPayments.Should().HaveCount(1);
            var payment = payroll.DeductionPayments.First();
            payment.DeductionRuleId.Should().Be(ruleId);
            payment.Amount.Should().Be(amount);
            payment.AppliedAt.Should().Be(appliedAt);
        }

        [Fact]
        public void AddProjectPayment_WhenInDraftState_ShouldAddPayment()
        {
            // Arrange
            var payroll = CreateValidPayroll();
            var projectId = 123;
            var amount = 400m;
            var paidAt = DateTime.UtcNow;

            // Act
            payroll.AddProjectPayment(projectId, amount, paidAt);

            // Assert
            payroll.ProjectPayments.Should().HaveCount(1);
            var payment = payroll.ProjectPayments.First();
            payment.RedmineProjectId.Should().Be(projectId);
            payment.Amount.Should().Be(amount);
            payment.PaidAt.Should().Be(paidAt);
        }

        [Fact]
        public void CompleteWorkflow_ShouldFollowCorrectStateTransitions()
        {
            // Arrange
            var payroll = CreateValidPayrollWithComponents();

            // Act & Assert - Initial state
            payroll.Status.Should().Be(PayrollStatus.Draft);

            // Act & Assert - After calculation
            payroll.MarkAsCalculated();
            payroll.Status.Should().Be(PayrollStatus.Calculated);
            payroll.GrossAmount.Should().BeGreaterThan(0);
            payroll.NetAmount.Should().BeGreaterThanOrEqualTo(0);

            // Act & Assert - After approval
            payroll.Approve();
            payroll.Status.Should().Be(PayrollStatus.Approved);

            // Act & Assert - After payment
            payroll.MarkAsPaid();
            payroll.Status.Should().Be(PayrollStatus.Paid);
        }

        [Fact]
        public void Calculation_WithMultipleComponents_ShouldCalculateCorrectAmounts()
        {
            // Arrange
            var payroll = CreateValidPayroll();
            
            payroll.AddComponent(new PayrollComponent(
                PayrollComponentType.BaseSalary,
                PayrollComponentCategory.Earning,
                "Base Salary",
                2000m,
                Guid.NewGuid()));
            
            payroll.AddComponent(new PayrollComponent(
                PayrollComponentType.Overtime,
                PayrollComponentCategory.Earning,
                "Overtime",
                300m,
                Guid.NewGuid()));
            
            payroll.AddComponent(new PayrollComponent(
                PayrollComponentType.LegalDeduction,
                PayrollComponentCategory.Deduction,
                "Tax",
                200m,
                Guid.NewGuid()));
            
            payroll.AddComponent(new PayrollComponent(
                PayrollComponentType.LegalDeduction,
                PayrollComponentCategory.Deduction,
                "Social Security",
                150m,
                Guid.NewGuid()));

            // Act
            payroll.MarkAsCalculated();

            // Assert
            payroll.GrossAmount.Should().Be(2300m);
            payroll.TotalDeductions.Should().Be(350m);
            payroll.NetAmount.Should().Be(1950m);
        }

        [Fact]
        public void PaymentCollections_ShouldBeReadOnly()
        {
            // Arrange
            var payroll = CreateValidPayroll();

            // Act & Assert - Verify assignable to IReadOnlyCollection
            payroll.Components.Should().BeAssignableTo<IReadOnlyCollection<PayrollComponent>>();
            payroll.MilestonePayments.Should().BeAssignableTo<IReadOnlyCollection<MilestonePayment>>();
            payroll.AguinaldoPayments.Should().BeAssignableTo<IReadOnlyCollection<AguinaldoPayment>>();
            payroll.VacationPayments.Should().BeAssignableTo<IReadOnlyCollection<VacationPayment>>();
            payroll.ProductivityPayments.Should().BeAssignableTo<IReadOnlyCollection<ProductivityPayment>>();
            payroll.OvertimePayments.Should().BeAssignableTo<IReadOnlyCollection<OvertimePayment>>();
            payroll.DeductionPayments.Should().BeAssignableTo<IReadOnlyCollection<DeductionPayment>>();
            payroll.ProjectPayments.Should().BeAssignableTo<IReadOnlyCollection<ProjectPayment>>();

            // Act & Assert
            payroll.Components.Should().NotBeOfType<List<PayrollComponent>>();
            
            // Act & Assert
            payroll.Components.Should().BeOfType<ReadOnlyCollection<PayrollComponent>>();
        }

        private static Payroll CreateValidPayroll()
        {
            return new Payroll(
                Guid.NewGuid(),
                new DateTime(2024, 1, 1),
                new DateTime(2024, 1, 31));
        }

        private static Payroll CreateValidPayrollWithComponents()
        {
            var payroll = CreateValidPayroll();
            payroll.AddComponent(new PayrollComponent(
                PayrollComponentType.BaseSalary,
                PayrollComponentCategory.Earning,
                "Base Salary",
                1000m,
                Guid.NewGuid()));
            return payroll;
        }
    }
}